export const flags = {
    'Bahrain': require('../assets/countryFlags/bahrain.jpg'),
    'Saudi Arabia': require('../assets/countryFlags/saudiarabia.jpg'),
    'Australia': require('../assets/countryFlags/australia.jpg'),
    'Azerbaijan': require('../assets/countryFlags/azerbaijan.jpg'),
    'USA': require('../assets/countryFlags/usa.jpg'),
    'United States': require('../assets/countryFlags/usa.jpg'),
    'Monaco': require('../assets/countryFlags/monaco.jpg'),
    'Spain': require('../assets/countryFlags/spain.jpg'),
    'Canada': require('../assets/countryFlags/canada.jpg'),
    'Austria': require('../assets/countryFlags/austria.jpg'),
    'UK': require('../assets/countryFlags/uk.jpg'),
    'Hungary': require('../assets/countryFlags/hungary.jpg'),
    'Belgium': require('../assets/countryFlags/belgium.jpg'),
    'Netherlands': require('../assets/countryFlags/netherlands.jpg'),
    'Italy': require('../assets/countryFlags/italy.jpg'),
    'Singapore': require('../assets/countryFlags/singapore.jpg'),
    'Japan': require('../assets/countryFlags/japan.jpg'),
    'Qatar': require('../assets/countryFlags/qatar.jpg'),
    'Mexico': require('../assets/countryFlags/mexico.jpg'),
    'Brazil': require('../assets/countryFlags/brazil.jpg'),
    'UAE': require('../assets/countryFlags/uae.jpg'),
}